version: '2.1'

services:

  # Service definition for Consul cluster with a minimum of 3 nodes.
  # For local development we use Compose v2 so that we have an automatically
  # created user-defined network and internal DNS for the name "consul".
  # Nodes will use Docker DNS for the service (passed in via the CONSUL
  # env var) to find each other and bootstrap the cluster.
  consul:
    build: .
    image: vickov/autopilotpattern-consul:latest
    restart: always
    mem_limit: 128m
    network_mode: host
    ports:
        - 8500
    environment:
      - CONSUL=10.0.0.45 10.0.0.46
      - CONSUL_DATACENTER_NAME=dc1
      - CONSUL_IP=10.0.0.45
